// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWvBPmkNHFzRxRJemovBoZaV1CZSmoI0',
    appId: '1:146003479826:web:19c4613fad05e4e87e37cb',
    messagingSenderId: '146003479826',
    projectId: 'arabic-5041c',
    authDomain: 'arabic-5041c.firebaseapp.com',
    storageBucket: 'arabic-5041c.appspot.com',
    measurementId: 'G-G1FVPZMS0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVDgDFhymyzbwN0z8HdnT7qbWUM8OPdk',
    appId: '1:146003479826:android:ed66f9063ca2d1f17e37cb',
    messagingSenderId: '146003479826',
    projectId: 'arabic-5041c',
    storageBucket: 'arabic-5041c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE4YdbbGMstZ7GbHBd7homfa8FaYxts7M',
    appId: '1:146003479826:ios:41530a37b858a1367e37cb',
    messagingSenderId: '146003479826',
    projectId: 'arabic-5041c',
    storageBucket: 'arabic-5041c.appspot.com',
    androidClientId: '146003479826-oiei7rgo4bjkqbs0scbehd5ruql762nj.apps.googleusercontent.com',
    iosClientId: '146003479826-9j4t1n1qm2f1k4lnamrrqqb11c83p0gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.arabicOpen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE4YdbbGMstZ7GbHBd7homfa8FaYxts7M',
    appId: '1:146003479826:ios:41530a37b858a1367e37cb',
    messagingSenderId: '146003479826',
    projectId: 'arabic-5041c',
    storageBucket: 'arabic-5041c.appspot.com',
    androidClientId: '146003479826-oiei7rgo4bjkqbs0scbehd5ruql762nj.apps.googleusercontent.com',
    iosClientId: '146003479826-9j4t1n1qm2f1k4lnamrrqqb11c83p0gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.arabicOpen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWvBPmkNHFzRxRJemovBoZaV1CZSmoI0',
    appId: '1:146003479826:web:1c3dd82245602b5e7e37cb',
    messagingSenderId: '146003479826',
    projectId: 'arabic-5041c',
    authDomain: 'arabic-5041c.firebaseapp.com',
    storageBucket: 'arabic-5041c.appspot.com',
    measurementId: 'G-WEV2VMW76V',
  );

}